-- MySQL Script generated by MySQL Workbench
-- Wed Jun 14 12:53:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema checkpoint
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `checkpoint` ;

-- -----------------------------------------------------
-- Schema checkpoint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint` DEFAULT CHARACTER SET utf8 ;
USE `checkpoint` ;

-- -----------------------------------------------------
-- Table `mydb`.`info2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`info2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `info2` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`info 3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`info 3` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `info3` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`info1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`info1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `info1` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`objet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `info1_id` INT NOT NULL,
  `info2_id` INT NOT NULL,
  `info 3_id` INT NOT NULL,
  `more_info` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`, `info1_id`, `info2_id`, `info 3_id`),
  INDEX `fk_objet_info2_idx` (`info2_id` ASC) VISIBLE,
  INDEX `fk_objet_info 31_idx` (`info 3_id` ASC) VISIBLE,
  INDEX `fk_objet_info11_idx` (`info1_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
