-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 21:45:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema checkpoint
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `checkpoint` ;

-- -----------------------------------------------------
-- Schema checkpoint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint` DEFAULT CHARACTER SET utf8mb3 ;
USE `checkpoint` ;

-- -----------------------------------------------------
-- Table `checkpoint`.`console`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`console` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checkpoint`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checkpoint`.`objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`objet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `consoleId` INT NOT NULL,
  `prixId` INT NOT NULL,
  `genreId` INT NOT NULL,
  `info` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `consoleId`, `prixId`, `genreId`),
  INDEX `fk_objet_info2_idx` (`prixId` ASC) VISIBLE,
  INDEX `fk_objet_info 31_idx` (`genreId` ASC) VISIBLE,
  INDEX `fk_objet_info11_idx` (`consoleId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checkpoint`.`prix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`prix` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checkpoint`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `admin` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;